App\Entity\Adress:
  properties:
    type:
      - NotBlank: ~
    number:
      - NotBlank: ~
    name:
      - NotBlank: ~
    citty:
      - NotBlank: ~
    postalCode:
      - NotBlank: ~
    client:
      - NotBlank: ~